/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package maas

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"slices"
	"strings"
	"time"

	"github.com/go-logr/logr"
	kservev1alpha2 "github.com/kserve/kserve/pkg/apis/serving/v1alpha2"
	llmdv1alpha2 "github.com/llm-d/llm-d-router/apix/v1alpha2"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/equality"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/types"
	"knative.dev/pkg/kmeta"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	maasv1alpha1 "github.com/opendatahub-io/models-as-a-service/maas-controller/api/maas/v1alpha1"
	"github.com/opendatahub-io/models-as-a-service/maas-controller/pkg/oteljson"
	"github.com/opendatahub-io/models-as-a-service/maas-controller/pkg/platform/tenantreconcile"
)

const (
	// inferenceObjectiveNameMaxLength is the longest generated InferenceObjective name, the
	// limit kmeta.ChildName enforces.
	inferenceObjectiveNameMaxLength = 63
	inferenceObjectiveNamePrefix    = "maas"
	// inferenceObjectiveNameHashLength is the number of hex characters of the identity
	// hash kept in generated names. It is never truncated.
	inferenceObjectiveNameHashLength = 10

	inferenceObjectiveCRD = "inferenceobjectives.llm-d.ai"

	defaultInferencePoolGroup = "inference.networking.k8s.io"
	defaultInferencePoolKind  = "InferencePool"

	// Ownership metadata on generated InferenceObjectives. The subscription name and tenant
	// name are annotations because they are not guaranteed to fit in a label value; the
	// tenant key also differs from tenantreconcile.LabelTenantName, which marks
	// AITenant-managed resources.
	labelSubscriptionNamespace       = "maas.opendatahub.io/subscription-namespace"
	labelSubscriptionUID             = "maas.opendatahub.io/subscription-uid"
	annotationSubscriptionName       = "maas.opendatahub.io/subscription-name"
	annotationInferenceObjTenantName = "maas.opendatahub.io/tenant-name"
	inferenceObjectiveComponent      = "inference-objective"

	// inferenceObjectiveConflictRequeue rechecks a name held by a foreign object. The
	// InferenceObjective watch only sees objects carrying our labels.
	inferenceObjectiveConflictRequeue = 5 * time.Minute

	eventReasonInferenceObjectiveConflict = "InferenceObjectiveConflict"
	eventReasonInferenceObjectiveFailed   = "InferenceObjectiveFailed"
	eventReasonInferencePoolUnsupported   = "InferencePoolUnsupported"
	eventReasonInferencePoolNotOnGateway  = "InferencePoolNotOnTenantGateway"
)

// inferenceObjectiveOwnerLabels are the labels every generated InferenceObjective carries.
func inferenceObjectiveOwnerLabels() map[string]string {
	return map[string]string{
		"app.kubernetes.io/managed-by": "maas-controller",
		"app.kubernetes.io/part-of":    "maas-subscription",
		"app.kubernetes.io/component":  inferenceObjectiveComponent,
	}
}

// hasInferenceObjectiveOwnerLabels reports whether labels mark an InferenceObjective as
// generated by this controller.
func hasInferenceObjectiveOwnerLabels(labels map[string]string) bool {
	for k, v := range inferenceObjectiveOwnerLabels() {
		if labels[k] != v {
			return false
		}
	}
	return true
}

// inferenceObjectiveName returns the deterministic InferenceObjective name for a
// subscription and InferencePool: "maas-<tenant>-<subscription>-<pool>-<hash>". The hash
// of the full identities keeps names unique; kmeta.ChildName keeps it as the suffix and,
// when the name is too long, truncates the readable part. The name does not depend on
// spec.inferencePriority, so it is stable across priority changes. It also excludes the
// pool's API group and kind: KServe keeps the pool name stable but reports the group of
// whichever pool API version the gateway currently accepts.
func inferenceObjectiveName(tenantName string, subscription, pool types.NamespacedName) string {
	identity := strings.Join([]string{
		tenantName,
		subscription.Namespace, subscription.Name,
		pool.Namespace, pool.Name,
	}, "\x00")
	sum := sha256.Sum256([]byte(identity))
	hash := hex.EncodeToString(sum[:])[:inferenceObjectiveNameHashLength]

	// The tenant, subscription, and pool names are Kubernetes object names, so the joined
	// string is already a valid name. ChildName alone hashes only names that are too long,
	// so short names would collide (tenant "a-b" + subscription "c" vs tenant "a" +
	// subscription "b-c"), and the subscription namespace is not in the readable part. The
	// identity hash covers both.
	parent := strings.Join([]string{inferenceObjectiveNamePrefix, tenantName, subscription.Name, pool.Name}, "-")
	return kmeta.ChildName(parent, "-"+hash)
}

// flowControlTenantName returns the AITenant name for a subscription namespace. It falls
// back to the default tenant name when the namespace has no tenant config.
func flowControlTenantName(ctx context.Context, c client.Reader, namespace string) (string, error) {
	tenant, err := fetchTenantForNamespace(ctx, c, namespace)
	if err != nil {
		if apierrors.IsNotFound(err) || apimeta.IsNoMatchError(err) {
			return tenantreconcile.TenantNameFor(nil)
		}
		return "", err
	}
	return tenant.name()
}

// inferencePoolRef is the InferencePool an InferenceObjective points at. The pool is
// always in the objective's namespace.
type inferencePoolRef struct {
	Group string
	Kind  string
	Name  string
}

// poolResolutionReason explains why resolveModelInferencePool returned no pool.
type poolResolutionReason string

const (
	// poolResolutionPending: the pool is not observed yet; a watch re-triggers reconcile.
	poolResolutionPending poolResolutionReason = "Pending"
	// poolResolutionNotApplicable: the model is not served through an inference scheduler.
	poolResolutionNotApplicable poolResolutionReason = "NotApplicable"
	// poolResolutionUnsupported: the model has a scheduler topology objectives cannot target.
	poolResolutionUnsupported poolResolutionReason = "Unsupported"
)

// modelPoolResolution is the result of resolveModelInferencePool. Pool is set when the
// model has a single observed pool; otherwise Reason and Message explain why not.
type modelPoolResolution struct {
	Pool    *inferencePoolRef
	Reason  poolResolutionReason
	Message string
}

// resolveModelInferencePool returns the InferencePool observed for a MaaSModelRef. The pool
// lives in the model's namespace, alongside its LLMInferenceService. A non-nil error is a
// transient lookup failure that should be retried; missing resources are reported as
// Pending without an error because the MaaSModelRef and LLMInferenceService watches
// re-trigger reconciliation.
func (r *MaaSSubscriptionReconciler) resolveModelInferencePool(ctx context.Context, modelNamespace, modelName string) (modelPoolResolution, error) {
	model := &maasv1alpha1.MaaSModelRef{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: modelNamespace, Name: modelName}, model); err != nil {
		if apierrors.IsNotFound(err) {
			return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("MaaSModelRef %s/%s not found", modelNamespace, modelName)}, nil
		}
		return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("failed to get MaaSModelRef: %v", err)},
			fmt.Errorf("failed to get MaaSModelRef %s/%s: %w", modelNamespace, modelName, err)
	}
	if model.Spec.ModelRef.Kind != "LLMInferenceService" {
		return modelPoolResolution{
			Reason:  poolResolutionNotApplicable,
			Message: fmt.Sprintf("model kind %s is not served through an inference scheduler", model.Spec.ModelRef.Kind),
		}, nil
	}

	llmisvc := &kservev1alpha2.LLMInferenceService{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: model.Namespace, Name: model.Spec.ModelRef.Name}, llmisvc); err != nil {
		if apierrors.IsNotFound(err) || apimeta.IsNoMatchError(err) {
			return modelPoolResolution{
				Reason:  poolResolutionPending,
				Message: fmt.Sprintf("LLMInferenceService %s/%s not found", model.Namespace, model.Spec.ModelRef.Name),
			}, nil
		}
		return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("failed to get LLMInferenceService: %v", err)},
			fmt.Errorf("failed to get LLMInferenceService %s/%s: %w", model.Namespace, model.Spec.ModelRef.Name, err)
	}

	router := llmisvc.Status.Router
	if router != nil && router.Group != nil && activeRoutingGroupMembers(router.Group) > 1 {
		return modelPoolResolution{
			Reason: poolResolutionUnsupported,
			Message: fmt.Sprintf("LLMInferenceService %s/%s splits traffic across routing group %s; request priority requires a single InferencePool",
				llmisvc.Namespace, llmisvc.Name, router.Group.Name),
		}, nil
	}
	if router != nil && router.Scheduler != nil && router.Scheduler.InferencePool != nil {
		observed := router.Scheduler.InferencePool
		// An InferenceObjective can only reference a pool in its own namespace, and KServe
		// creates or references pools in the LLMInferenceService namespace.
		if observed.Namespace != nil && *observed.Namespace != "" && string(*observed.Namespace) != llmisvc.Namespace {
			return modelPoolResolution{
				Reason: poolResolutionUnsupported,
				Message: fmt.Sprintf("InferencePool %s/%s is not in the LLMInferenceService namespace %s",
					*observed.Namespace, observed.Name, llmisvc.Namespace),
			}, nil
		}
		pool := &inferencePoolRef{
			Group: string(observed.Group),
			Kind:  string(observed.Kind),
			Name:  string(observed.Name),
		}
		if pool.Group == "" {
			pool.Group = defaultInferencePoolGroup
		}
		if pool.Kind == "" {
			pool.Kind = defaultInferencePoolKind
		}
		return modelPoolResolution{Pool: pool}, nil
	}

	// The scheduler can come from the service spec or from a referenced config, so rely on
	// the observed status: a ready service without a pool is served without a scheduler.
	if llmisvcReadyStatus(llmisvc) != string(corev1.ConditionTrue) {
		return modelPoolResolution{
			Reason:  poolResolutionPending,
			Message: fmt.Sprintf("waiting for LLMInferenceService %s/%s to report an InferencePool", llmisvc.Namespace, llmisvc.Name),
		}, nil
	}
	return modelPoolResolution{
		Reason:  poolResolutionNotApplicable,
		Message: fmt.Sprintf("LLMInferenceService %s/%s is not served through an inference scheduler", llmisvc.Namespace, llmisvc.Name),
	}, nil
}

// activeRoutingGroupMembers counts routing group members that receive traffic.
func activeRoutingGroupMembers(group *kservev1alpha2.GroupStatus) int {
	active := 0
	for _, m := range group.Members {
		if !m.Stopped && m.Weight > 0 {
			active++
		}
	}
	return active
}

// desiredObjective is one InferenceObjective a subscription needs: one per InferencePool,
// shared by every referenced model served from that pool.
type desiredObjective struct {
	Pool       inferencePoolRef
	TenantName string
	Priority   int32
	// Models are the "namespace/name" model refs served from Pool, for logs and events.
	Models []string
}

// desiredInferenceObjectives returns the InferenceObjectives the subscription needs, keyed
// by name and namespace. complete is false when a lookup failed, so the set may be missing
// objectives that should exist; the caller must then not delete anything. A failure for
// one model does not stop the others.
func (r *MaaSSubscriptionReconciler) desiredInferenceObjectives(ctx context.Context, sub *maasv1alpha1.MaaSSubscription) (map[types.NamespacedName]*desiredObjective, bool, error) {
	desired := make(map[types.NamespacedName]*desiredObjective)
	if sub.Spec.InferencePriority == nil {
		return desired, true, nil
	}
	priority := *sub.Spec.InferencePriority

	refs := make([]string, 0, len(sub.Spec.ModelRefs))
	for _, ref := range sub.Spec.ModelRefs {
		key := ref.Namespace + "/" + ref.Name
		if !slices.Contains(refs, key) {
			refs = append(refs, key)
		}
	}
	slices.Sort(refs)

	complete := true
	var errs []error

	// Resolved lazily, once: only models with an observed pool need them.
	var (
		gatewayRef      maasv1alpha1.TenantGatewayRef
		gatewayResolved bool
		tenantName      string
		tenantResolved  bool
	)

	for _, key := range refs {
		modelNamespace, modelName, _ := strings.Cut(key, "/")

		res, err := r.resolveModelInferencePool(ctx, modelNamespace, modelName)
		if err != nil {
			complete = false
			errs = append(errs, fmt.Errorf("model %s: %w", key, err))
			continue
		}
		if res.Pool == nil {
			if res.Reason == poolResolutionUnsupported {
				r.warnf(sub, eventReasonInferencePoolUnsupported, "Request priority is not applied to model %s: %s", key, res.Message)
			}
			continue
		}

		if !gatewayResolved {
			gatewayRef, err = tenantGatewayRefForNamespace(ctx, r.Client, sub.Namespace,
				r.DefaultTenantNamespace, r.GatewayName, r.GatewayNamespace, r.TenantNamespaceDiscoveryEnabled)
			if err != nil {
				r.warnf(sub, eventReasonInferenceObjectiveFailed, "Failed to resolve tenant gateway for namespace %s: %v", sub.Namespace, err)
				return desired, false, errors.Join(append(errs, fmt.Errorf("failed to resolve tenant gateway for namespace %s: %w", sub.Namespace, err))...)
			}
			gatewayResolved = true
		}
		routeName, routeNamespace, err := findHTTPRouteForModel(ctx, r.Client, modelNamespace, modelName)
		if err == nil {
			err = validateHTTPRouteReferencesGateway(ctx, r.Client, routeName, routeNamespace, gatewayRef)
		}
		switch {
		case err == nil:
		case errors.Is(err, ErrModelNotFound), errors.Is(err, ErrHTTPRouteNotFound):
			continue
		case errors.Is(err, ErrHTTPRouteNotOnTenantGateway):
			r.warnf(sub, eventReasonInferencePoolNotOnGateway, "Request priority is not applied to model %s: %v", key, err)
			continue
		default:
			complete = false
			errs = append(errs, fmt.Errorf("model %s: gateway check: %w", key, err))
			continue
		}

		if !tenantResolved {
			tenantName, err = flowControlTenantName(ctx, r.Client, sub.Namespace)
			if err != nil {
				r.warnf(sub, eventReasonInferenceObjectiveFailed, "Failed to resolve tenant for namespace %s: %v", sub.Namespace, err)
				return desired, false, errors.Join(append(errs, fmt.Errorf("failed to resolve tenant for namespace %s: %w", sub.Namespace, err))...)
			}
			tenantResolved = true
		}

		objKey := types.NamespacedName{
			Namespace: modelNamespace,
			Name: inferenceObjectiveName(tenantName, client.ObjectKeyFromObject(sub),
				types.NamespacedName{Namespace: modelNamespace, Name: res.Pool.Name}),
		}
		if d, ok := desired[objKey]; ok {
			d.Models = append(d.Models, key)
			continue
		}
		desired[objKey] = &desiredObjective{Pool: *res.Pool, TenantName: tenantName, Priority: priority, Models: []string{key}}
	}
	return desired, complete, errors.Join(errs...)
}

// inferenceObjectiveApplyOutcome is the result of applyInferenceObjective.
type inferenceObjectiveApplyOutcome int

const (
	inferenceObjectiveApplied inferenceObjectiveApplyOutcome = iota
	// inferenceObjectiveConflict: a foreign object holds the name; it is left untouched.
	inferenceObjectiveConflict
	// inferenceObjectiveAPIUnavailable: the InferenceObjective API is not served.
	inferenceObjectiveAPIUnavailable
)

// isAPIUnavailable reports whether err means the InferenceObjective API is not served.
func isAPIUnavailable(err error) bool {
	return apimeta.IsNoMatchError(err) || apierrors.IsNotFound(err)
}

// buildInferenceObjective returns the InferenceObjective for a desired entry.
func buildInferenceObjective(sub *maasv1alpha1.MaaSSubscription, key types.NamespacedName, d *desiredObjective) *llmdv1alpha2.InferenceObjective {
	labels := inferenceObjectiveOwnerLabels()
	labels[labelSubscriptionNamespace] = sub.Namespace
	labels[labelSubscriptionUID] = string(sub.UID)
	return &llmdv1alpha2.InferenceObjective{
		ObjectMeta: metav1.ObjectMeta{
			Name:      key.Name,
			Namespace: key.Namespace,
			Labels:    labels,
			Annotations: map[string]string{
				annotationSubscriptionName:       sub.Name,
				annotationInferenceObjTenantName: d.TenantName,
			},
		},
		Spec: inferenceObjectiveSpec(d),
	}
}

// inferenceObjectiveSpec returns the spec for a desired entry.
func inferenceObjectiveSpec(d *desiredObjective) llmdv1alpha2.InferenceObjectiveSpec {
	priority := d.Priority
	return llmdv1alpha2.InferenceObjectiveSpec{
		Priority: &priority,
		PoolRef: llmdv1alpha2.PoolObjectReference{
			Group: llmdv1alpha2.Group(d.Pool.Group),
			Kind:  llmdv1alpha2.Kind(d.Pool.Kind),
			Name:  llmdv1alpha2.ObjectName(d.Pool.Name),
		},
	}
}

// applyInferenceObjective creates or updates the InferenceObjective for one desired entry.
// It never touches an object it does not own or one that opted out of management.
func (r *MaaSSubscriptionReconciler) applyInferenceObjective(
	ctx context.Context,
	log logr.Logger,
	sub *maasv1alpha1.MaaSSubscription,
	key types.NamespacedName,
	d *desiredObjective,
) (inferenceObjectiveApplyOutcome, error) {
	log = log.WithValues("inferenceObjective", key.String(), "models", d.Models)
	desired := buildInferenceObjective(sub, key, d)

	existing := &llmdv1alpha2.InferenceObjective{}
	err := r.Get(ctx, key, existing)
	switch {
	case apimeta.IsNoMatchError(err):
		return inferenceObjectiveAPIUnavailable, nil
	case apierrors.IsNotFound(err):
		if err := r.Create(ctx, desired); err != nil {
			if isAPIUnavailable(err) {
				return inferenceObjectiveAPIUnavailable, nil
			}
			return inferenceObjectiveApplied, fmt.Errorf("failed to create InferenceObjective %s: %w", key, err)
		}
		log.Info("InferenceObjective created", "priority", d.Priority, "pool", d.Pool.Name)
		return inferenceObjectiveApplied, nil
	case err != nil:
		return inferenceObjectiveApplied, fmt.Errorf("failed to get InferenceObjective %s: %w", key, err)
	}

	if !existing.GetDeletionTimestamp().IsZero() {
		return inferenceObjectiveApplied, fmt.Errorf("InferenceObjective %s is being deleted; will recreate it", key)
	}
	labels := existing.GetLabels()
	if !hasInferenceObjectiveOwnerLabels(labels) {
		r.warnf(sub, eventReasonInferenceObjectiveConflict,
			"InferenceObjective %s already exists and is not managed by maas-controller; request priority is not applied to %s",
			key, strings.Join(d.Models, ", "))
		return inferenceObjectiveConflict, nil
	}
	if labels[labelSubscriptionNamespace] != sub.Namespace || existing.GetAnnotations()[annotationSubscriptionName] != sub.Name {
		r.warnf(sub, eventReasonInferenceObjectiveConflict,
			"InferenceObjective %s belongs to subscription %s/%s; request priority is not applied to %s",
			key, labels[labelSubscriptionNamespace], existing.GetAnnotations()[annotationSubscriptionName], strings.Join(d.Models, ", "))
		return inferenceObjectiveConflict, nil
	}
	if !isManaged(existing) {
		log.Info("InferenceObjective opted out, skipping update")
		return inferenceObjectiveApplied, nil
	}

	// Merge our metadata over the existing object. This also adopts an objective left by
	// an earlier subscription with the same name by rewriting the UID label.
	snapshot := existing.DeepCopy()
	maps.Copy(existing.Labels, desired.Labels)
	if existing.Annotations == nil {
		existing.Annotations = make(map[string]string)
	}
	maps.Copy(existing.Annotations, desired.Annotations)
	existing.Spec = desired.Spec

	if equality.Semantic.DeepEqual(snapshot.ObjectMeta, existing.ObjectMeta) && equality.Semantic.DeepEqual(snapshot.Spec, existing.Spec) {
		return inferenceObjectiveApplied, nil
	}
	if err := r.Update(ctx, existing); err != nil {
		return inferenceObjectiveApplied, fmt.Errorf("failed to update InferenceObjective %s: %w", key, err)
	}
	log.Info("InferenceObjective updated", "priority", d.Priority, "pool", d.Pool.Name,
		"adopted", snapshot.GetLabels()[labelSubscriptionUID] != string(sub.UID))
	return inferenceObjectiveApplied, nil
}

// reconcileInferenceObjectives creates, updates, and deletes the subscription's
// InferenceObjectives. conflict is true when a foreign object holds a name we need, so the
// caller can recheck later. Obsolete objectives are deleted only when the desired set is
// complete, so a transient lookup failure never removes a working objective. Errors are
// returned for retry; they never change the subscription phase.
func (r *MaaSSubscriptionReconciler) reconcileInferenceObjectives(ctx context.Context, log logr.Logger, sub *maasv1alpha1.MaaSSubscription) (bool, error) {
	if r.inferenceObjectivesUnavailable.Load() {
		return false, nil
	}
	desired, complete, err := r.desiredInferenceObjectives(ctx, sub)
	var errs []error
	if err != nil {
		errs = append(errs, err)
	}

	keys := slices.SortedFunc(maps.Keys(desired), func(a, b types.NamespacedName) int {
		return strings.Compare(a.String(), b.String())
	})
	keep := make(map[types.NamespacedName]struct{}, len(desired))
	conflict := false
	for _, key := range keys {
		keep[key] = struct{}{}
		outcome, applyErr := r.applyInferenceObjective(ctx, log, sub, key, desired[key])
		switch outcome {
		case inferenceObjectiveAPIUnavailable:
			log.V(1).Info("InferenceObjective API is not served; skipping request priority")
			return conflict, errors.Join(errs...)
		case inferenceObjectiveConflict:
			conflict = true
		case inferenceObjectiveApplied:
		}
		if applyErr != nil {
			// AlreadyExists and Conflict mean the cache is behind our own last write; the
			// retry resolves them, so they are not worth a Warning event.
			if !apierrors.IsAlreadyExists(applyErr) && !apierrors.IsConflict(applyErr) {
				r.warnf(sub, eventReasonInferenceObjectiveFailed, "%v", applyErr)
			}
			errs = append(errs, applyErr)
		}
	}

	if complete {
		if err := r.deleteOwnedInferenceObjectives(ctx, log, sub, keep); err != nil {
			errs = append(errs, err)
		}
	}
	return conflict, errors.Join(errs...)
}

// deleteOwnedInferenceObjectives deletes the subscription's InferenceObjectives that are not
// in keep. A nil keep deletes all of them, for finalizer cleanup. It only uses labels and
// annotations, so it works without tenant or gateway lookups. Objectives that opted out of
// management are left in place.
func (r *MaaSSubscriptionReconciler) deleteOwnedInferenceObjectives(ctx context.Context, log logr.Logger, sub *maasv1alpha1.MaaSSubscription, keep map[types.NamespacedName]struct{}) error {
	list := &llmdv1alpha2.InferenceObjectiveList{}
	selector := client.MatchingLabels(inferenceObjectiveOwnerLabels())
	selector[labelSubscriptionNamespace] = sub.Namespace
	// Read from the API server: the cache may not have seen an objective created moments
	// ago, and missing it here during finalizer cleanup would orphan it.
	if err := r.APIReader.List(ctx, list, selector); err != nil {
		if isAPIUnavailable(err) {
			return nil
		}
		return fmt.Errorf("failed to list InferenceObjectives for subscription %s/%s: %w", sub.Namespace, sub.Name, err)
	}

	var errs []error
	for i := range list.Items {
		obj := &list.Items[i]
		if obj.GetAnnotations()[annotationSubscriptionName] != sub.Name {
			continue
		}
		key := client.ObjectKeyFromObject(obj)
		if _, ok := keep[key]; ok {
			continue
		}
		if !isManaged(obj) {
			log.Info("InferenceObjective opted out, skipping deletion", "inferenceObjective", key.String())
			continue
		}
		uid := obj.GetUID()
		if err := r.Delete(ctx, obj, client.Preconditions{UID: &uid}); err != nil && !apierrors.IsNotFound(err) {
			errs = append(errs, fmt.Errorf("failed to delete InferenceObjective %s: %w", key, err))
			continue
		}
		log.Info("InferenceObjective deleted", "inferenceObjective", key.String())
	}
	return errors.Join(errs...)
}

// warnf records a Warning event on the subscription. SetupWithManager always sets Recorder.
func (r *MaaSSubscriptionReconciler) warnf(sub *maasv1alpha1.MaaSSubscription, reason, messageFmt string, args ...any) {
	r.Recorder.Eventf(sub, nil, corev1.EventTypeWarning, reason, "ReconcileInferenceObjectives", messageFmt, args...)
}

// mapLLMISvcToMaaSSubscriptions returns reconcile requests for the MaaSSubscriptions that
// reference MaaSModelRefs backed by the LLMInferenceService.
func (r *MaaSSubscriptionReconciler) mapLLMISvcToMaaSSubscriptions(ctx context.Context, obj client.Object) []reconcile.Request {
	var models maasv1alpha1.MaaSModelRefList
	if err := r.List(ctx, &models, client.InNamespace(obj.GetNamespace())); err != nil {
		oteljson.FromContext(ctx).Error(err, "failed to list MaaSModelRefs for LLMInferenceService", "llmisvc", qualifiedName(obj.GetNamespace(), obj.GetName()))
		return nil
	}
	seen := make(map[types.NamespacedName]struct{})
	var requests []reconcile.Request
	for i := range models.Items {
		m := &models.Items[i]
		if m.Spec.ModelRef.Kind != "LLMInferenceService" || m.Spec.ModelRef.Name != obj.GetName() {
			continue
		}
		for _, req := range r.mapMaaSModelRefToMaaSSubscriptions(ctx, m) {
			if _, ok := seen[req.NamespacedName]; ok {
				continue
			}
			seen[req.NamespacedName] = struct{}{}
			requests = append(requests, req)
		}
	}
	return requests
}

// llmisvcRouterStatusChangedPredicate passes Create/Delete events and Update events where the
// LLMInferenceService's observed router topology or Ready condition changed.
type llmisvcRouterStatusChangedPredicate struct {
	predicate.Funcs
}

func (llmisvcRouterStatusChangedPredicate) Update(e event.UpdateEvent) bool {
	if e.ObjectOld == nil || e.ObjectNew == nil {
		return true
	}
	if oldObj, ok := e.ObjectOld.(*kservev1alpha2.LLMInferenceService); ok {
		newObj, ok := e.ObjectNew.(*kservev1alpha2.LLMInferenceService)
		if !ok {
			return true
		}
		return !equality.Semantic.DeepEqual(oldObj.Status.Router, newObj.Status.Router) ||
			llmisvcReadyStatus(oldObj) != llmisvcReadyStatus(newObj)
	}
	// Dynamic watches registered after the CRD appears deliver unstructured objects.
	oldU, ok := e.ObjectOld.(*unstructured.Unstructured)
	if !ok {
		return true
	}
	newU, ok := e.ObjectNew.(*unstructured.Unstructured)
	if !ok {
		return true
	}
	oldRouter, _, _ := unstructured.NestedFieldNoCopy(oldU.Object, "status", "router")
	newRouter, _, _ := unstructured.NestedFieldNoCopy(newU.Object, "status", "router")
	return !equality.Semantic.DeepEqual(oldRouter, newRouter) ||
		unstructuredLLMIsvcReadyStatus(oldU) != unstructuredLLMIsvcReadyStatus(newU)
}

// mapInferenceObjectiveToSubscription maps a generated InferenceObjective to the
// subscription named by its ownership metadata.
func mapInferenceObjectiveToSubscription(_ context.Context, obj client.Object) []reconcile.Request {
	namespace := obj.GetLabels()[labelSubscriptionNamespace]
	name := obj.GetAnnotations()[annotationSubscriptionName]
	if namespace == "" || name == "" {
		return nil
	}
	return []reconcile.Request{{NamespacedName: types.NamespacedName{Namespace: namespace, Name: name}}}
}

// ownedInferenceObjectivePredicate passes events for InferenceObjectives generated by this
// controller. Create and Delete pass so a deleted objective is recreated; Update passes on
// spec, label, or annotation changes and drops status-only writes by the scheduler.
func ownedInferenceObjectivePredicate() predicate.Funcs {
	owned := func(obj client.Object) bool {
		return obj != nil && hasInferenceObjectiveOwnerLabels(obj.GetLabels())
	}
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool { return owned(e.Object) },
		DeleteFunc: func(e event.DeleteEvent) bool { return owned(e.Object) },
		UpdateFunc: func(e event.UpdateEvent) bool {
			if !owned(e.ObjectOld) && !owned(e.ObjectNew) {
				return false
			}
			if e.ObjectOld == nil || e.ObjectNew == nil {
				return true
			}
			return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration() ||
				!maps.Equal(e.ObjectOld.GetLabels(), e.ObjectNew.GetLabels()) ||
				!maps.Equal(e.ObjectOld.GetAnnotations(), e.ObjectNew.GetAnnotations())
		},
		GenericFunc: func(event.GenericEvent) bool { return false },
	}
}

// mapTenantConfigToMaaSSubscriptions enqueues the subscriptions in a MaasTenantConfig or
// legacy Tenant namespace. The tenant name and gateway are part of the objective's identity
// and placement, so a tenant change re-runs the InferenceObjective pass.
func (r *MaaSSubscriptionReconciler) mapTenantConfigToMaaSSubscriptions(ctx context.Context, obj client.Object) []reconcile.Request {
	subList := &maasv1alpha1.MaaSSubscriptionList{}
	if err := r.List(ctx, subList, client.InNamespace(obj.GetNamespace())); err != nil {
		oteljson.FromContext(ctx).Error(err, "failed to list MaaSSubscriptions for tenant config change",
			"tenantConfig", qualifiedName(obj.GetNamespace(), obj.GetName()))
		return nil
	}
	subList.Items = filterSubscriptionsByTenantNamespace(ctx, r.Client, subList.Items, r.DefaultTenantNamespace, r.TenantNamespaceDiscoveryEnabled)
	requests := make([]reconcile.Request, len(subList.Items))
	for i, sub := range subList.Items {
		requests[i] = reconcile.Request{NamespacedName: types.NamespacedName{Namespace: sub.Namespace, Name: sub.Name}}
	}
	return requests
}

// subscriptionsWithInferencePriority returns reconcile requests for every subscription that
// sets spec.inferencePriority. It runs when the InferenceObjective CRD appears; a list
// error is returned so the caller retries.
func (r *MaaSSubscriptionReconciler) subscriptionsWithInferencePriority(ctx context.Context) ([]reconcile.Request, error) {
	subList := &maasv1alpha1.MaaSSubscriptionList{}
	if err := r.List(ctx, subList); err != nil {
		return nil, fmt.Errorf("failed to list MaaSSubscriptions: %w", err)
	}
	subList.Items = filterSubscriptionsByTenantNamespace(ctx, r.Client, subList.Items, r.DefaultTenantNamespace, r.TenantNamespaceDiscoveryEnabled)
	var requests []reconcile.Request
	for _, sub := range subList.Items {
		if sub.Spec.InferencePriority != nil {
			requests = append(requests, reconcile.Request{NamespacedName: types.NamespacedName{Namespace: sub.Namespace, Name: sub.Name}})
		}
	}
	return requests, nil
}
