FROM registry.access.redhat.com/ubi9/go-toolset@sha256:e8938564f866174a6d79e55dfe577c2ed184b1f53e91d782173fb69b07ce69ef AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

USER root
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o maas-api ./cmd/

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:bb08f2300cb8d12a7eb91dddf28ea63692b3ec99e7f0fa71a1b300f2756ea829


WORKDIR /app

COPY --from=builder /app/maas-api .

# Make binary executable and fix permissions for OpenShift
RUN chmod +x maas-api && \
    chgrp -R 0 /app && \
    chmod -R g=u /app

# Use a non-root user (OpenShift will assign random UID)
USER 1001

EXPOSE 8080

CMD ["./maas-api"]

LABEL com.redhat.component="odh-maas-api-rhel9" \
      name="rhoai/odh-maas-api-rhel9" \
      description="odh-maas-api" \
      summary="odh-maas-api" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-maas-api" \
      io.k8s.description="odh-maas-api" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"